steps:
  - name: 'bash'
    args: ['echo', 'Starting build for $PROJECT_ID...']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ghl-exporter', '.']
options:
  logging: 'NONE'
timeout: '1200s'
images:
  - 'gcr.io/$PROJECT_ID/ghl-exporter'
